export { getREL_LOVE_GENERALVariants } from './REL_LOVE_GENERAL.js';
export { getREL_LOVE_BREAKUP_PAINVariants } from './REL_LOVE_BREAKUP_PAIN.js';

export { getRELATIONSHIP_GENERALVariants } from './RELATIONSHIP_GENERAL.js';
export { getRELATIONSHIP_STABILITYVariants } from './RELATIONSHIP_STABILITY.js';
export { getRELATIONSHIP_MARRIAGE_TIMINGVariants } from './RELATIONSHIP_MARRIAGE_TIMING.js';
export { getRELATIONSHIP_CONFLICT_PATCHUPVariants } from './RELATIONSHIP_CONFLICT_PATCHUP.js';
export { getRELATIONSHIP_EMOTIONAL_DISTANCEVariants } from './RELATIONSHIP_EMOTIONAL_DISTANCE.js';
export { getFAMILY_RELATIONS_GENERALVariants } from './FAMILY_RELATIONS_GENERAL.js';
export { getFAMILY_CONFLICT_PRESSUREVariants } from './FAMILY_CONFLICT_PRESSURE.js';
export { getLONG_TERM_RELATIONSHIP_BONDVariants } from './LONG_TERM_RELATIONSHIP_BOND.js';


