import {
  getMONEY_BUSINESS_GENERALVariants,
  getMONEY_BUSINESS_GROWTH_WINVariants,
  getMONEY_BUSINESS_LOSS_RISKVariants,
  getMONEY_BUSINESS_STARTVariants,
  getMONEY_BUSINESS_PARTNERSHIP_COMPLEXVariants,
  getMONEY_JOB_STABILITYVariants,
  getMONEY_JOB_PROMOTION_WINVariants,
  getFINANCE_GENERALVariants,
  getFINANCE_INCOME_FLOWVariants,
  getFINANCE_EXPENSE_PRESSUREVariants,
  getFINANCE_SAVINGS_GROWTHVariants,
  getFINANCE_DEBT_LOANVariants,
  getFINANCE_INVESTMENT_TIMINGVariants,
  getFINANCE_SUDDEN_GAIN_LOSSVariants,
  getFINANCE_LONG_TERM_WEALTHVariants,
} from './money/index.js';

import {
  getCAREER_GOVT_JOB_TENDENCYVariants,
  getCAREER_PRIVATE_JOB_PATHVariants,
  getCAREER_GENERALVariants,
  getCAREER_STABILITYVariants,
  getCAREER_GROWTH_PROMOTIONVariants,
  getCAREER_JOB_CHANGEVariants,
  getCAREER_WORKPLACE_CONFLICTVariants,
  getCAREER_SKILL_STAGNATIONVariants,
} from './career/index.js';

import {
  getREL_LOVE_GENERALVariants,
  getREL_LOVE_BREAKUP_PAINVariants,
  getRELATIONSHIP_GENERALVariants,
  getRELATIONSHIP_STABILITYVariants,
  getRELATIONSHIP_MARRIAGE_TIMINGVariants,
  getRELATIONSHIP_CONFLICT_PATCHUPVariants,
  getRELATIONSHIP_EMOTIONAL_DISTANCEVariants,
  getFAMILY_RELATIONS_GENERALVariants,
  getFAMILY_CONFLICT_PRESSUREVariants,
  getLONG_TERM_RELATIONSHIP_BONDVariants,
} from './relationships/index.js';

import {
  getPROGENY_GENERALVariants,
  getPROGENY_TIMING_WINDOWVariants,
  getPROGENY_DELAY_BLOCKVariants,
  getPROGENY_MULTIPLE_TENDENCYVariants,
  getPROGENY_PARENTING_PRESSUREVariants,
  getPROGENY_EMOTIONAL_BONDVariants,
} from './family_home/index.js';

import {
  getHEALTH_GENERALVariants,
  getHEALTH_ENERGY_LEVELVariants,
  getHEALTH_STRESS_PRESSUREVariants,
  getHEALTH_RECOVERY_PHASEVariants,
  getHEALTH_IMMUNITY_BALANCEVariants,
  getHEALTH_LIFESTYLE_IMPACTVariants,
  getHEALTH_WORK_HEALTH_TRADEOFFVariants,
  getHEALTH_LONG_TERM_VITALITYVariants,
} from './health/index.js';

function withGlobalVariantCodes(pointCode, getVariantsFn) {
  return () => {
    const variants = getVariantsFn();
    if (!Array.isArray(variants)) return variants;

    return variants.map((v, idx) => {
      const local = v?.code || `P${String(idx + 1).padStart(2, '0')}`;
      const globalCode = local.startsWith(`${pointCode}__`)
        ? local
        : `${pointCode}__${local}`;
      return { ...v, code: globalCode };
    });
  };
}

export const planetaryRegistry = {
  MONEY_BUSINESS_GENERAL: withGlobalVariantCodes('MONEY_BUSINESS_GENERAL', getMONEY_BUSINESS_GENERALVariants),
  MONEY_BUSINESS_GROWTH_WIN: withGlobalVariantCodes('MONEY_BUSINESS_GROWTH_WIN', getMONEY_BUSINESS_GROWTH_WINVariants),
  MONEY_BUSINESS_LOSS_RISK: withGlobalVariantCodes('MONEY_BUSINESS_LOSS_RISK', getMONEY_BUSINESS_LOSS_RISKVariants),
  MONEY_BUSINESS_START: withGlobalVariantCodes('MONEY_BUSINESS_START', getMONEY_BUSINESS_STARTVariants),
  MONEY_BUSINESS_PARTNERSHIP_COMPLEX: withGlobalVariantCodes(
    'MONEY_BUSINESS_PARTNERSHIP_COMPLEX',
    getMONEY_BUSINESS_PARTNERSHIP_COMPLEXVariants
  ),

  MONEY_JOB_STABILITY: withGlobalVariantCodes('MONEY_JOB_STABILITY', getMONEY_JOB_STABILITYVariants),
  MONEY_JOB_PROMOTION_WIN: withGlobalVariantCodes('MONEY_JOB_PROMOTION_WIN', getMONEY_JOB_PROMOTION_WINVariants),

  FINANCE_GENERAL: withGlobalVariantCodes('FINANCE_GENERAL', getFINANCE_GENERALVariants),
  FINANCE_INCOME_FLOW: withGlobalVariantCodes('FINANCE_INCOME_FLOW', getFINANCE_INCOME_FLOWVariants),
  FINANCE_EXPENSE_PRESSURE: withGlobalVariantCodes('FINANCE_EXPENSE_PRESSURE', getFINANCE_EXPENSE_PRESSUREVariants),
  FINANCE_SAVINGS_GROWTH: withGlobalVariantCodes('FINANCE_SAVINGS_GROWTH', getFINANCE_SAVINGS_GROWTHVariants),
  FINANCE_DEBT_LOAN: withGlobalVariantCodes('FINANCE_DEBT_LOAN', getFINANCE_DEBT_LOANVariants),
  FINANCE_INVESTMENT_TIMING: withGlobalVariantCodes('FINANCE_INVESTMENT_TIMING', getFINANCE_INVESTMENT_TIMINGVariants),
  FINANCE_SUDDEN_GAIN_LOSS: withGlobalVariantCodes('FINANCE_SUDDEN_GAIN_LOSS', getFINANCE_SUDDEN_GAIN_LOSSVariants),
  FINANCE_LONG_TERM_WEALTH: withGlobalVariantCodes('FINANCE_LONG_TERM_WEALTH', getFINANCE_LONG_TERM_WEALTHVariants),

  CAREER_GOVT_JOB_TENDENCY: withGlobalVariantCodes('CAREER_GOVT_JOB_TENDENCY', getCAREER_GOVT_JOB_TENDENCYVariants),
  CAREER_PRIVATE_JOB_PATH: withGlobalVariantCodes('CAREER_PRIVATE_JOB_PATH', getCAREER_PRIVATE_JOB_PATHVariants),

  CAREER_GENERAL: withGlobalVariantCodes('CAREER_GENERAL', getCAREER_GENERALVariants),
  CAREER_STABILITY: withGlobalVariantCodes('CAREER_STABILITY', getCAREER_STABILITYVariants),
  CAREER_GROWTH_PROMOTION: withGlobalVariantCodes('CAREER_GROWTH_PROMOTION', getCAREER_GROWTH_PROMOTIONVariants),
  CAREER_JOB_CHANGE: withGlobalVariantCodes('CAREER_JOB_CHANGE', getCAREER_JOB_CHANGEVariants),
  CAREER_WORKPLACE_CONFLICT: withGlobalVariantCodes(
    'CAREER_WORKPLACE_CONFLICT',
    getCAREER_WORKPLACE_CONFLICTVariants
  ),
  CAREER_SKILL_STAGNATION: withGlobalVariantCodes('CAREER_SKILL_STAGNATION', getCAREER_SKILL_STAGNATIONVariants),

  REL_LOVE_GENERAL: withGlobalVariantCodes('REL_LOVE_GENERAL', getREL_LOVE_GENERALVariants),
  REL_LOVE_BREAKUP_PAIN: withGlobalVariantCodes('REL_LOVE_BREAKUP_PAIN', getREL_LOVE_BREAKUP_PAINVariants),

  RELATIONSHIP_GENERAL: withGlobalVariantCodes('RELATIONSHIP_GENERAL', getRELATIONSHIP_GENERALVariants),
  RELATIONSHIP_STABILITY: withGlobalVariantCodes('RELATIONSHIP_STABILITY', getRELATIONSHIP_STABILITYVariants),
  RELATIONSHIP_MARRIAGE_TIMING: withGlobalVariantCodes(
    'RELATIONSHIP_MARRIAGE_TIMING',
    getRELATIONSHIP_MARRIAGE_TIMINGVariants
  ),
  RELATIONSHIP_CONFLICT_PATCHUP: withGlobalVariantCodes(
    'RELATIONSHIP_CONFLICT_PATCHUP',
    getRELATIONSHIP_CONFLICT_PATCHUPVariants
  ),
  RELATIONSHIP_EMOTIONAL_DISTANCE: withGlobalVariantCodes(
    'RELATIONSHIP_EMOTIONAL_DISTANCE',
    getRELATIONSHIP_EMOTIONAL_DISTANCEVariants
  ),
  FAMILY_RELATIONS_GENERAL: withGlobalVariantCodes('FAMILY_RELATIONS_GENERAL', getFAMILY_RELATIONS_GENERALVariants),
  FAMILY_CONFLICT_PRESSURE: withGlobalVariantCodes('FAMILY_CONFLICT_PRESSURE', getFAMILY_CONFLICT_PRESSUREVariants),
  LONG_TERM_RELATIONSHIP_BOND: withGlobalVariantCodes('LONG_TERM_RELATIONSHIP_BOND', getLONG_TERM_RELATIONSHIP_BONDVariants),

  PROGENY_GENERAL: withGlobalVariantCodes('PROGENY_GENERAL', getPROGENY_GENERALVariants),
  PROGENY_TIMING_WINDOW: withGlobalVariantCodes('PROGENY_TIMING_WINDOW', getPROGENY_TIMING_WINDOWVariants),
  PROGENY_DELAY_BLOCK: withGlobalVariantCodes('PROGENY_DELAY_BLOCK', getPROGENY_DELAY_BLOCKVariants),
  PROGENY_MULTIPLE_TENDENCY: withGlobalVariantCodes(
    'PROGENY_MULTIPLE_TENDENCY',
    getPROGENY_MULTIPLE_TENDENCYVariants
  ),
  PROGENY_PARENTING_PRESSURE: withGlobalVariantCodes(
    'PROGENY_PARENTING_PRESSURE',
    getPROGENY_PARENTING_PRESSUREVariants
  ),
  PROGENY_EMOTIONAL_BOND: withGlobalVariantCodes('PROGENY_EMOTIONAL_BOND', getPROGENY_EMOTIONAL_BONDVariants),

  HEALTH_GENERAL: withGlobalVariantCodes('HEALTH_GENERAL', getHEALTH_GENERALVariants),
  HEALTH_ENERGY_LEVEL: withGlobalVariantCodes('HEALTH_ENERGY_LEVEL', getHEALTH_ENERGY_LEVELVariants),
  HEALTH_STRESS_PRESSURE: withGlobalVariantCodes('HEALTH_STRESS_PRESSURE', getHEALTH_STRESS_PRESSUREVariants),
  HEALTH_RECOVERY_PHASE: withGlobalVariantCodes('HEALTH_RECOVERY_PHASE', getHEALTH_RECOVERY_PHASEVariants),
  HEALTH_IMMUNITY_BALANCE: withGlobalVariantCodes('HEALTH_IMMUNITY_BALANCE', getHEALTH_IMMUNITY_BALANCEVariants),
  HEALTH_LIFESTYLE_IMPACT: withGlobalVariantCodes('HEALTH_LIFESTYLE_IMPACT', getHEALTH_LIFESTYLE_IMPACTVariants),
  HEALTH_WORK_HEALTH_TRADEOFF: withGlobalVariantCodes('HEALTH_WORK_HEALTH_TRADEOFF', getHEALTH_WORK_HEALTH_TRADEOFFVariants),
  HEALTH_LONG_TERM_VITALITY: withGlobalVariantCodes('HEALTH_LONG_TERM_VITALITY', getHEALTH_LONG_TERM_VITALITYVariants),
};

export default planetaryRegistry;


